In [1]:
from sklearn import datasets
import numpy as np

In [2]:
iris =datasets.load_iris()
X = iris.data[:100,[2,3]]
y = iris.target[0:100]
print('class labels:',np.unique(y))

class labels: [0 1]


In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1,stratify=y)
print("Labels counts in y:",np.bincount(y))

Labels counts in y: [50 50]


In [4]:
print("Labels counts in testing y:",np.bincount(y_test))

Labels counts in testing y: [12 13]


In [5]:
print("Labels counts in training y:",np.bincount(y_train))

Labels counts in training y: [38 37]


In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [7]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(max_iter=100, n_iter_no_change=50, eta0=0.1,random_state=1)
ppn.fit(X_train_std,y_train)


Perceptron(eta0=0.1, max_iter=100, n_iter_no_change=50, random_state=1)

In [8]:
y_predict = ppn.predict(X_test_std)
print(y_predict)

[1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]


In [9]:
print('misclassified examples: %d' %(y_test!=y_predict).sum())

misclassified examples: 0


In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_new = iris.data[:,[2,3]]
y_new = iris.target

"""I personally thinks that perceptron classifier works well only on binary classification tasks.
if we want to make multiclass classidications then we need to use DECISION TREE CLASSIFIER"""

'I personally thinks that perceptron classifier works well only on binary classification tasks.\nif we want to make multiclass classidications then we need to use DECISION TREE CLASSIFIER'

In [11]:
X_new_train,X_new_test,y_new_train,y_new_test = train_test_split(X_new,y_new,random_state=1,stratify=y_new)
sn = StandardScaler()
X_new_train_std = sn.fit_transform(X_new_train)
X_new_test_std = sn.fit_transform(X_new_test)
dtree = DecisionTreeClassifier().fit(X_new_train_std,y_new_train)
dpredictions = dtree.predict(X_new_test_std)

In [12]:
print(dpredictions)

[2 0 0 0 1 0 1 1 0 1 2 2 2 1 2 1 2 1 1 1 1 2 2 1 0 0 0 1 2 0 0 2 1 0 0 1 2
 2]


In [13]:
print('misclassified examples: %d'  %(y_new_test!=dpredictions).sum())

misclassified examples: 1


In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_new_test,dpredictions)

In [15]:
print(cm)

[[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]


In [18]:
print(y_new)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [17]:
print('the accuracy is: %.3f' %accuracy_score(y_new_test,dpredictions))

the accuracy is: 0.974


In [22]:
'''plot the decision region'''
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
def plot_decision_region(X,y,classifier,test_idx=None,resolution=0.02):
    markers =('s','x','o','^','v')
    colors = ('red','blue','green','yellow','purple')
    cmap = ListedColormap(colors[:len(np.unique(y_new))])
    x1_min,x1_max = X[:,0].min()-1,X[:,0].max()+1
    x2_min,x2_max = X[:,1].min()-1,X[:,1].max()+1
    xx1, xx2 = np.meshgrid(np.arange(x1_min,x1_max,resolution),np.arange(x2_min,x2_max,resolution))
    

In [27]:
resolution = 0.01
x1_min,x1_max = X[:,0].min()-1,X[:,0].max()+1
x2_min,x2_max = X[:,1].min()-1,X[:,1].max()+1
xx1, xx2 = np.meshgrid(np.arange(x1_min,x1_max,resolution),np.arange(x2_min,x2_max,resolution))

In [32]:
print(x1_min,x1_max,x2_min,x2_max)

0.0 6.1 -0.9 2.8


In [35]:
xx1 = np.meshgrid(np.arange(x1_min,x1_max,resolution))
print(xx1)

[array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09,
       1.1 , 1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 ,
       1.21, 1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31,
       1.32, 1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42,
       1.43, 1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1

In [36]:
xx2 = np.meshgrid(np.arange(x2_min,x2_max,resolution))

In [37]:
print(xx2)

[array([-9.00000000e-01, -8.90000000e-01, -8.80000000e-01, -8.70000000e-01,
       -8.60000000e-01, -8.50000000e-01, -8.40000000e-01, -8.30000000e-01,
       -8.20000000e-01, -8.10000000e-01, -8.00000000e-01, -7.90000000e-01,
       -7.80000000e-01, -7.70000000e-01, -7.60000000e-01, -7.50000000e-01,
       -7.40000000e-01, -7.30000000e-01, -7.20000000e-01, -7.10000000e-01,
       -7.00000000e-01, -6.90000000e-01, -6.80000000e-01, -6.70000000e-01,
       -6.60000000e-01, -6.50000000e-01, -6.40000000e-01, -6.30000000e-01,
       -6.20000000e-01, -6.10000000e-01, -6.00000000e-01, -5.90000000e-01,
       -5.80000000e-01, -5.70000000e-01, -5.60000000e-01, -5.50000000e-01,
       -5.40000000e-01, -5.30000000e-01, -5.20000000e-01, -5.10000000e-01,
       -5.00000000e-01, -4.90000000e-01, -4.80000000e-01, -4.70000000e-01,
       -4.60000000e-01, -4.50000000e-01, -4.40000000e-01, -4.30000000e-01,
       -4.20000000e-01, -4.10000000e-01, -4.00000000e-01, -3.90000000e-01,
       -3.80000000e-01, 